/**
* Author: Nelson Victor Cruz Hdez
* Alias: vicco
* Mail: victor.cruz.isc@gmail.com | victor@bitso.com
* Description: Simple C calling method class
* Date: 29/10/2017
*/

/*
* Generated with the following command:
* javah -jni <java class that wraps C methods>
* e.j. javah -jni JavaCWrapper
*/

/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class JavaCWrapper */

#ifndef _Included_JavaCWrapper
#define _Included_JavaCWrapper
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     JavaCWrapper
 * Method:    additionFromC
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_JavaCWrapper_additionFromC
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     JavaCWrapper
 * Method:    substractionFromC
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_JavaCWrapper_substractionFromC
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     JavaCWrapper
 * Method:    divisionFromC
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_JavaCWrapper_divisionFromC
  (JNIEnv *, jobject, jdouble, jdouble);

/*
 * Class:     JavaCWrapper
 * Method:    aboutFromC
 * Signature: ()V
 */
JNIEXPORT void JNICALL Java_JavaCWrapper_aboutFromC
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
